apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: .
    repoURL: 'https://github.com/joelchan24/vault-argocd.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
