apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    name: 'default'
    namespace: vault
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/joelchan24/vault-argocd.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

