apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1 # Adjust based on your production needs
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        args:
        - "server"
        - "-config=/vault/config/vault.hcl"
        ports:
        - containerPort: 8200
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    app: vault
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
  type: ClusterIP # Adjust based on your network requirements
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |-
    ui = true
    storage "file" {
      path = "/vault/data"
    }
    listener "tcp" {
      address     = "[::]:8200"
      tls_disable = 1
    }
    api_addr = "http://127.0.0.1:8200"
