apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
    # valueFiles:
    # - values.yaml # Specify your Helm values file
    repoURL: 'https://charts.external-secrets.io' # Replace with your Helm chart repository URL
    chart: external-secrets
    targetRevision: 0.9.13 # Replace with your desired chart version
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
